export const titulos = [
                { selector: '.ensaladas h1', es: 'ENSALADAS', en: 'SALADS', fr: 'SALADES' },
                { selector: '.arroces h1', es: 'ARROCES', en: 'RICE DISHES', fr: 'PLATS DE RIZ' },
                { selector: '.carnes h1', es: 'CARNES', en: 'MEATS', fr: 'VIANDES' },
                { selector: '.pescados h1', es: 'PESCADOS', en: 'FISH', fr: 'POISSONS' },
                { selector: '.croquetas h1', es: 'CROQUETAS (9 UND)', en: 'CROQUETTES (9 UND)', fr: 'CROQUETTES (9 UND)' },
                { selector: '.raciones h1', es: 'RACIONES', en: 'SIDE DISHES', fr: 'ACCOMPAGNEMENTS' },
                { selector: '.baguettes h1', es: 'BAGUETTES', en: 'BAGUETTES', fr: 'BAGUETTES' },
                { selector: '.tostas h1', es: 'TOSTAS', en: 'TOASTS', fr: 'TARTINES' },
                { selector: '.hamburguesas h1', es: 'HAMBURGUESAS', en: 'HAMBURGERS', fr: 'BURGERS' },
                { selector: '.sandwichs h1', es: 'SANDWICHS', en: 'SANDWICHES', fr: 'SANDWICHS' },
                { selector: '.pizzas h1', es: 'PIZZAS', en: 'PIZZAS', fr: 'PIZZAS' },
                { selector: '.postres h1', es: 'POSTRES', en: 'DESSERTS', fr: 'DESSERTS' },
                { selector: '.vinos h1', es: 'VINOS', en: 'WINES', fr: 'VINS' },
            ];
